spring:
  datasource:
    url: jdbc:h2:mem:jpadb
    driverClassName: org.h2.Driver
    username: sa
    password: mypass
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.path: /public/h2-console
    console.enabled: true

app:    
  authentication:
    sign-up-url: /api/user
    jwtSecret: ENC(ggogoTOfHrNKmhoQAs9f+cvxAiOQWAAe3T6OC1tOq9ddvUf3uX/hSHPa8ljLK95y)
    expirationTime: 864000000 # 10 days
    jwtTokenPrefix: Bearer
    jwtTokenField: Authorization
  surge-price:
    timeWindownInSeconds: 3600 # 1 hour
    viewThreshold: 10
    priceIncreasePercent: 10
    
springdoc:
  swagger-ui:
    path: /public/swagger/swagger-ui.html
  api-docs:
    path: /public/swagger/api-docs
    